repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-ast

  # Notebook formatting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-isort
        additional_dependencies: [ isort ]
        args: [ --nbqa-mutate ]

      - id: nbqa-pyupgrade
        additional_dependencies: [ pyupgrade ]
        args: [ --py39-plus, --nbqa-mutate ]


  - repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
